version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
  
  php:
      build: ./server/php
      container_name: php
      restart: always
      depends_on:
        - redis
        
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
