version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  php:
    build: ./server/php
    container_name: php
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - redis

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 8998:3306
    environment:
      # MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: highway
      MARIADB_PASSWORD: 400254/**!@$%&8(#)(spogjḱ-=-=00dd).;/[}]
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/conf:/etc/mysql/conf.d

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8999:8080
    depends_on:
      - mariadb
