version: "3.8"

services:
  nginx:
      image: nginx:latest
      container_name: nginx
      restart: always
      ports:
        - "8080:80"
      volumes:
        - .:/var/www
        - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
      build: ./server/php
      container_name: php
      restart: always

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
